RUN \
    --mount=type=bind,from=ghcr.io/ublue-os/akmods:bazzite-41-6.11.10-304.bazzite.fc41.x86_64,src=/rpms,dst=/tmp/akmods-rpms,rw \
    --mount=type=bind,from=ghcr.io/ublue-os/akmods-extra:bazzite-41-6.11.10-304.bazzite.fc41.x86_64,src=/rpms,dst=/tmp/akmods-extra-rpms,rw \
    sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/_copr_ublue-os-akmods.repo \
    && rpm-ostree install \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm \
    && rpm-ostree install \
        /tmp/akmods-rpms/kmods/*xone*.rpm \
        /tmp/akmods-rpms/kmods/*v4l2loopback*.rpm \
    && rpm-ostree uninstall \
        rpmfusion-free-release \
        rpmfusion-nonfree-release \
    && sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/_copr_ublue-os-akmods.repo \
    && ostree container commit