RUN \
    --mount=type=bind,from=ghcr.io/ublue-os/bazzite-kernel:41-6.11.10-304.bazzite.fc41.x86_64,src=/tmp/rpms,dst=/tmp/kernel-rpms,rw \
    rpm-ostree override replace \
        --experimental \
        /tmp/kernel-rpms/kernel-[0-9]*.rpm \
        /tmp/kernel-rpms/kernel-core-*.rpm \
        /tmp/kernel-rpms/kernel-modules-*.rpm \
        /tmp/kernel-rpms/kernel-uki-virt-*.rpm \
        && ostree container commit